export const CmpPrescoutTableColumns = [
  {
    field: 'scoutName',
    title: 'Scout',
    width: 150,
    frozen: true,
    cssClass: 'tabulator-col-vertical tabulator-col-vertical-flip',
    //hozAlign: 'right',
  },
  {
    field: 'teamNumber',
    title: 'Team',
    width: 50,
    frozen: true,
    cssClass: 'tabulator-col-vertical tabulator-col-vertical-flip',
    hozAlign: 'right',
  },
  {
    field: 'matchNumber',
    title: 'Match',
    width: 50,
    frozen: true,
    cssClass: 'tabulator-col-vertical tabulator-col-vertical-flip',
    hozAlign: 'right',
  },
  {
    field: 'eventName',
    title: 'Last Event Name',
    width: 250,
    frozen: true,
    cssClass: 'tabulator-col-vertical tabulator-col-vertical-flip',
    //hozAlign: 'right',
  },
  {
    field: 'eventCode',
    title: 'Last Event',
    width: 75,
    frozen: true,
    cssClass: 'tabulator-col-vertical tabulator-col-vertical-flip',
    //hozAlign: 'right',
  },

  {
    field: 'allianceColor',
    title: 'Alliance Color',
    width: 50,
    frozen: true,
    cssClass: 'tabulator-col-vertical tabulator-col-vertical-flip',
    //hozAlign: 'right',
  },
  {
    field: 'alliancePosition',
    title: 'Alliance Position',
    width: 50,
    frozen: true,
    cssClass: 'tabulator-col-vertical tabulator-col-vertical-flip',
    //hozAlign: 'right',
  },
  {
    field: '',
    title: 'Team Name',
    width: 50,
    frozen: true,
    cssClass: 'tabulator-col-vertical tabulator-col-vertical-flip',
    //hozAlign: 'right',
  },
  {
    field: 'matchVideo',
    title: 'Match Video Link',
    width: 300,
    frozen: true,
    cssClass: 'tabulator-col-vertical tabulator-col-vertical-flip',
    //hozAlign: 'right',
  },
  {
    field: 'leave',
    title: 'Leave',
    width: 150,
    frozen: true,
    cssClass: 'tabulator-col-vertical tabulator-col-vertical-flip',
    //hozAlign: 'right',
  },
  {
    field: 'endgame',
    title: 'Endgame',
    width: 150,
    frozen: true,
    cssClass: 'tabulator-col-vertical tabulator-col-vertical-flip',
    //hozAlign: 'right',
  },
];
