import { formatDateTemp } from './dcmp-prescout-table-formatters';

export const DcmpPrescoutTableColumns = [
  {
    field: 'teamNumber',
    title: 'Team',
    width: 50,
    frozen: true,
    cssClass: 'tabulator-col-vertical tabulator-col-vertical-flip',
    hozAlign: 'right',
  },
  {
    field: 'totalDcmpPoints',
    title: 'DCMP Points',
    width: 50,
    frozen: true,
    cssClass: 'tabulator-col-vertical tabulator-col-vertical-flip',
    hozAlign: 'right',
  },
  {
    field: 'dcmpLocked',
    title: 'Locked',
    width: 75,
    frozen: true,
    cssClass: 'tabulator-col-vertical tabulator-col-vertical-flip',
    //hozAlign: 'right',
  },
  {
    field: 'lastEventStartDate',
    title: 'Final Event Date',
    width: 100,
    frozen: true,
    cssClass: 'tabulator-col-vertical tabulator-col-vertical-flip',
    //hozAlign: 'right',
    formatter: formatDateTemp,
  },
  {
    field: 'eventName',
    title: 'Last Event Name',
    width: 250,
    frozen: true,
    cssClass: 'tabulator-col-vertical tabulator-col-vertical-flip',
    //hozAlign: 'right',
  },
  {
    field: 'eventCode',
    title: 'Last Event Code',
    width: 75,
    frozen: true,
    cssClass: 'tabulator-col-vertical tabulator-col-vertical-flip',
    //hozAlign: 'right',
  },
  {
    field: 'matchNumber',
    title: 'Match',
    width: 50,
    frozen: true,
    cssClass: 'tabulator-col-vertical tabulator-col-vertical-flip',
    hozAlign: 'right',
  },
  {
    field: 'allianceColor',
    title: 'Alliance Color',
    width: 50,
    frozen: true,
    cssClass: 'tabulator-col-vertical tabulator-col-vertical-flip',
    //hozAlign: 'right',
  },
  {
    field: 'alliancePosition',
    title: 'Alliance Position',
    width: 50,
    frozen: true,
    cssClass: 'tabulator-col-vertical tabulator-col-vertical-flip',
    //hozAlign: 'right',
  },
  {
    field: 'source',
    title: 'Source',
    width: 150,
    frozen: true,
    cssClass: 'tabulator-col-vertical tabulator-col-vertical-flip',
    //hozAlign: 'right',
  },
  {
    field: 'scoutName',
    title: 'Scout',
    width: 150,
    frozen: true,
    cssClass: 'tabulator-col-vertical tabulator-col-vertical-flip',
    //hozAlign: 'right',
  },
];
