CREATE TABLE "EventMatchTeams2025Result" (
	"Event_Match_Id" varchar(30) NOT NULL,
	"Alliance_Color" varchar(5) NOT NULL,
	"Alliance_Position" smallint NOT NULL,
	"Leave" varchar(20) NOT NULL,
	"Endgame" varchar(15) NOT NULL,
	"Created_At" timestamp DEFAULT now() NOT NULL,
	"Updated_At" timestamp DEFAULT now() NOT NULL,
	"Synced_At" timestamp
);
--> statement-breakpoint
CREATE TABLE "EventMatches2025Result" (
	"Event_Match_Id" varchar(30) NOT NULL,
	"Alliance_Color" varchar(5) NOT NULL,
	"Auto_L4_A" boolean NOT NULL,
	"Auto_L4_B" boolean NOT NULL,
	"Auto_L4_C" boolean NOT NULL,
	"Auto_L4_D" boolean NOT NULL,
	"Auto_L4_E" boolean NOT NULL,
	"Auto_L4_F" boolean NOT NULL,
	"Auto_L4_G" boolean NOT NULL,
	"Auto_L4_H" boolean NOT NULL,
	"Auto_L4_I" boolean NOT NULL,
	"Auto_L4_J" boolean NOT NULL,
	"Auto_L4_K" boolean NOT NULL,
	"Auto_L4_L" boolean NOT NULL,
	"Auto_L3_A" boolean NOT NULL,
	"Auto_L3_B" boolean NOT NULL,
	"Auto_L3_C" boolean NOT NULL,
	"Auto_L3_D" boolean NOT NULL,
	"Auto_L3_E" boolean NOT NULL,
	"Auto_L3_F" boolean NOT NULL,
	"Auto_L3_G" boolean NOT NULL,
	"Auto_L3_H" boolean NOT NULL,
	"Auto_L3_I" boolean NOT NULL,
	"Auto_L3_J" boolean NOT NULL,
	"Auto_L3_K" boolean NOT NULL,
	"Auto_L3_L" boolean NOT NULL,
	"Auto_L2_A" boolean NOT NULL,
	"Auto_L2_B" boolean NOT NULL,
	"Auto_L2_C" boolean NOT NULL,
	"Auto_L2_D" boolean NOT NULL,
	"Auto_L2_E" boolean NOT NULL,
	"Auto_L2_F" boolean NOT NULL,
	"Auto_L2_G" boolean NOT NULL,
	"Auto_L2_H" boolean NOT NULL,
	"Auto_L2_I" boolean NOT NULL,
	"Auto_L2_J" boolean NOT NULL,
	"Auto_L2_K" boolean NOT NULL,
	"Auto_L2_L" boolean NOT NULL,
	"Auto_L1" smallint NOT NULL,
	"Auto_Coral_Count" smallint NOT NULL,
	"Auto_Mobility_Points" smallint NOT NULL,
	"Auto_Points" smallint NOT NULL,
	"Auto_Coral_Points" smallint NOT NULL,
	"Teleop_L4_A" boolean NOT NULL,
	"Teleop_L4_B" boolean NOT NULL,
	"Teleop_L4_C" boolean NOT NULL,
	"Teleop_L4_D" boolean NOT NULL,
	"Teleop_L4_E" boolean NOT NULL,
	"Teleop_L4_F" boolean NOT NULL,
	"Teleop_L4_G" boolean NOT NULL,
	"Teleop_L4_H" boolean NOT NULL,
	"Teleop_L4_I" boolean NOT NULL,
	"Teleop_L4_J" boolean NOT NULL,
	"Teleop_L4_K" boolean NOT NULL,
	"Teleop_L4_L" boolean NOT NULL,
	"Teleop_L3_A" boolean NOT NULL,
	"Teleop_L3_B" boolean NOT NULL,
	"Teleop_L3_C" boolean NOT NULL,
	"Teleop_L3_D" boolean NOT NULL,
	"Teleop_L3_E" boolean NOT NULL,
	"Teleop_L3_F" boolean NOT NULL,
	"Teleop_L3_G" boolean NOT NULL,
	"Teleop_L3_H" boolean NOT NULL,
	"Teleop_L3_I" boolean NOT NULL,
	"Teleop_L3_J" boolean NOT NULL,
	"Teleop_L3_K" boolean NOT NULL,
	"Teleop_L3_L" boolean NOT NULL,
	"Teleop_L2_A" boolean NOT NULL,
	"Teleop_L2_B" boolean NOT NULL,
	"Teleop_L2_C" boolean NOT NULL,
	"Teleop_L2_D" boolean NOT NULL,
	"Teleop_L2_E" boolean NOT NULL,
	"Teleop_L2_F" boolean NOT NULL,
	"Teleop_L2_G" boolean NOT NULL,
	"Teleop_L2_H" boolean NOT NULL,
	"Teleop_L2_I" boolean NOT NULL,
	"Teleop_L2_J" boolean NOT NULL,
	"Teleop_L2_K" boolean NOT NULL,
	"Teleop_L2_L" boolean NOT NULL,
	"Teleop_L1" smallint NOT NULL,
	"Teleop_Coral_Count" smallint NOT NULL,
	"Teleop_Points" smallint NOT NULL,
	"Teleop_Coral_Points" smallint NOT NULL,
	"Algae_Points" smallint NOT NULL,
	"Net_Algae_Count" smallint NOT NULL,
	"Wall_Algae_Count" smallint NOT NULL,
	"Endgame_Barge_Points" smallint NOT NULL,
	"Auto_Bonus_Achieved" boolean NOT NULL,
	"Coral_Bonus_Achieved" boolean NOT NULL,
	"Barge_Bonus_Achieved" boolean NOT NULL,
	"Coopertition_Criteria_Met" boolean NOT NULL,
	"Foul_Count" smallint NOT NULL,
	"G206_Penalty" boolean NOT NULL,
	"G410_Penalty" boolean NOT NULL,
	"G418_Penalty" boolean NOT NULL,
	"G428_Penalty" boolean NOT NULL,
	"Anjust_Points" smallint NOT NULL,
	"Foul_Points" smallint NOT NULL,
	"RP" smallint NOT NULL,
	"Total_Points" smallint NOT NULL,
	"Created_At" timestamp DEFAULT now() NOT NULL,
	"Updated_At" timestamp DEFAULT now() NOT NULL,
	"Synced_At" timestamp
);
--> statement-breakpoint
ALTER TABLE "EventMatchTeams2025Result" ADD CONSTRAINT "EventMatchTeams2025Result_Event_Match_Id_EventMatches_Event_Match_Id_fk" FOREIGN KEY ("Event_Match_Id") REFERENCES "public"."EventMatches"("Event_Match_Id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "EventMatches2025Result" ADD CONSTRAINT "EventMatches2025Result_Event_Match_Id_EventMatches_Event_Match_Id_fk" FOREIGN KEY ("Event_Match_Id") REFERENCES "public"."EventMatches"("Event_Match_Id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "idx_u_eventmatchteams2025result" ON "EventMatchTeams2025Result" USING btree ("Event_Match_Id","Alliance_Color","Alliance_Position");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_u_eventmatches2025result" ON "EventMatches2025Result" USING btree ("Event_Match_Id","Alliance_Color");